services:
  tqa-mysql:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tqa 

  backend:
    image: tqa-backend 
    build: 
      context: ./backend 
      dockerfile: Dockerfile 
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      tqa-mysql:
        condition: service_healthy
    networks:
      - tqa 

  frontend:
    image: tqa-frontend
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    networks:
      - tqa  

volumes:
  mysql-data:
networks:
  tqa: 